name: Resources
on: repository_dispatch
jobs:
  resources:
    name: Update resources
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ github.event.action }}
    steps:
    - name: Read .nvmrc
      run: echo ::set-output name=nvmrc::$(cat .nvmrc)
      id: nvm
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '${{ steps.nvm.outputs.nvmrc }}'
    - name: Install dependencies
      run: |
        npm install
        pip install -r requirements.txt
    - name: Fetch resources
      run: |
        node scripts/dump-connectors.js $VERSION
    - name: Push changes
      run: |
        python scripts/push-connectors.py $VERSION
      env:
        GH_FA_TOKEN: ${{ secrets.GH_FA_TOKEN }}
