name: resources
on: repository_dispatch
jobs:
  resources:
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ github.event.action }}
    steps:
    - uses: actions/checkout@v1
    - uses: borales/actions-yarn@v2.0.0
      with:
        cmd: install
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: Update resources
      run: |
        node scripts/dump-connectors.js $VERSION
    - name: Push changes
      run: |
        python scripts/push-connectors.py $VERSION
      env:
        GH_FA_TOKEN: ${{ secrets.GH_FA_TOKEN }}
